DROP SCHEMA IF EXISTS tenant_zup CASCADE;
CREATE SCHEMA tenant_zup;
SET search_path TO tenant_zup;
CREATE TABLE USERS (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(30)
);

DROP SCHEMA IF EXISTS tenant_zupp CASCADE;
CREATE SCHEMA tenant_zupp;
SET search_path TO tenant_zupp;
CREATE TABLE USERS (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(30)
);