CREATE SCHEMA tenant_zup AUTHORIZATION DBA;
SET SCHEMA tenant_zup;
CREATE TABLE USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);

CREATE SCHEMA tenant_zupp AUTHORIZATION DBA;
SET SCHEMA tenant_zupp;
CREATE TABLE USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);