CREATE SCHEMA TENANT_1 AUTHORIZATION DBA;
CREATE SCHEMA TENANT_2 AUTHORIZATION DBA;

CREATE TABLE TENANT_1.USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);

CREATE TABLE TENANT_2.USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);