CREATE SCHEMA tenant_zup AUTHORIZATION DBA;
CREATE SCHEMA tenant_zupp AUTHORIZATION DBA;

CREATE TABLE tenant_zup.USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);

CREATE TABLE tenant_zupp.USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(30)
);